[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra
    -Werror
    -fstack-protector-strong
    -D CORE_DEBUG_LEVEL=0
    -Wno-missing-field-initializers
    -Wno-unused-parameter
    -Wno-unused-variable
    -D DISABLE_ALL_LIBRARY_WARNINGS
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=135
    -D TFT_HEIGHT=240
    -D CGRAM_OFFSET=1
    -D TFT_MOSI=19
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=16
    -D TFT_RST=23
    -D TFT_BL=4
    -D TOUCH_CS=22
    -D LOAD_GLCD=1
    -D USE_NIMBLE=1
lib_deps = 
    bodmer/TFT_eSPI@^2.5.43
    h2zero/NimBLE-Arduino@^1.4.1
    t-vk/ESP32 BLE Keyboard@^0.3.2
test_ignore = *

[env:native]
platform = native
lib_ldf_mode = off
lib_deps = throwtheswitch/Unity@^2.6.1
build_flags =
    -Wall
    -Wextra
    -Werror
    -fstack-protector-strong
    -I test
    -std=gnu++11
build_src_filter = +<*> -<hal.cpp> -<encoder_glue.cpp> -<encoder.cpp> -<main.cpp> -<pin_fsm_glue.cpp> -<integration_tests.cpp> -<display_manager.cpp> -<ble_manager.cpp> -<nvs_manager.cpp>
test_filter = *
test_build_src = yes
